
import { BibleBook } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // Velho Testamento
  { id: 'GEN', name: 'Gênesis', chapters: 50, testament: 'Velho' },
  { id: 'EXO', name: 'Êxodo', chapters: 40, testament: 'Velho' },
  { id: 'LEV', name: 'Levítico', chapters: 27, testament: 'Velho' },
  { id: 'NUM', name: 'Números', chapters: 36, testament: 'Velho' },
  { id: 'DEU', name: 'Deuteronômio', chapters: 34, testament: 'Velho' },
  { id: 'JOS', name: 'Josué', chapters: 24, testament: 'Velho' },
  { id: 'JDG', name: 'Juízes', chapters: 21, testament: 'Velho' },
  { id: 'RUT', name: 'Rute', chapters: 4, testament: 'Velho' },
  { id: '1SA', name: '1 Samuel', chapters: 31, testament: 'Velho' },
  { id: '2SA', name: '2 Samuel', chapters: 24, testament: 'Velho' },
  { id: '1KI', name: '1 Reis', chapters: 22, testament: 'Velho' },
  { id: '2KI', name: '2 Reis', chapters: 25, testament: 'Velho' },
  { id: '1CH', name: '1 Crônicas', chapters: 29, testament: 'Velho' },
  { id: '2CH', name: '2 Crônicas', chapters: 36, testament: 'Velho' },
  { id: 'EZR', name: 'Esdras', chapters: 10, testament: 'Velho' },
  { id: 'NEH', name: 'Neemias', chapters: 13, testament: 'Velho' },
  { id: 'EST', name: 'Ester', chapters: 10, testament: 'Velho' },
  { id: 'JOB', name: 'Jó', chapters: 42, testament: 'Velho' },
  { id: 'PSA', name: 'Salmos', chapters: 150, testament: 'Velho' },
  { id: 'PRO', name: 'Provérbios', chapters: 31, testament: 'Velho' },
  { id: 'ECC', name: 'Eclesiastes', chapters: 12, testament: 'Velho' },
  { id: 'SNG', name: 'Cânticos', chapters: 8, testament: 'Velho' },
  { id: 'ISA', name: 'Isaías', chapters: 66, testament: 'Velho' },
  { id: 'JER', name: 'Jeremias', chapters: 52, testament: 'Velho' },
  { id: 'LAM', name: 'Lamentações', chapters: 5, testament: 'Velho' },
  { id: 'EZK', name: 'Ezequiel', chapters: 48, testament: 'Velho' },
  { id: 'DAN', name: 'Daniel', chapters: 12, testament: 'Velho' },
  { id: 'HOS', name: 'Oseias', chapters: 14, testament: 'Velho' },
  { id: 'JOL', name: 'Joel', chapters: 3, testament: 'Velho' },
  { id: 'AMO', name: 'Amós', chapters: 9, testament: 'Velho' },
  { id: 'OBA', name: 'Obadias', chapters: 1, testament: 'Velho' },
  { id: 'JON', name: 'Jonas', chapters: 4, testament: 'Velho' },
  { id: 'MIC', name: 'Miqueias', chapters: 7, testament: 'Velho' },
  { id: 'NAM', name: 'Naum', chapters: 3, testament: 'Velho' },
  { id: 'HAB', name: 'Habacuque', chapters: 3, testament: 'Velho' },
  { id: 'ZEP', name: 'Sofonias', chapters: 3, testament: 'Velho' },
  { id: 'HAG', name: 'Ageu', chapters: 2, testament: 'Velho' },
  { id: 'ZEC', name: 'Zacarias', chapters: 14, testament: 'Velho' },
  { id: 'MAL', name: 'Malaquias', chapters: 4, testament: 'Velho' },
  
  // Novo Testamento
  { id: 'MAT', name: 'Mateus', chapters: 28, testament: 'Novo' },
  { id: 'MRK', name: 'Marcos', chapters: 16, testament: 'Novo' },
  { id: 'LUK', name: 'Lucas', chapters: 24, testament: 'Novo' },
  { id: 'JHN', name: 'João', chapters: 21, testament: 'Novo' },
  { id: 'ACT', name: 'Atos', chapters: 28, testament: 'Novo' },
  { id: 'ROM', name: 'Romanos', chapters: 16, testament: 'Novo' },
  { id: '1CO', name: '1 Coríntios', chapters: 16, testament: 'Novo' },
  { id: '2CO', name: '2 Coríntios', chapters: 13, testament: 'Novo' },
  { id: 'GAL', name: 'Gálatas', chapters: 6, testament: 'Novo' },
  { id: 'EPH', name: 'Efésios', chapters: 6, testament: 'Novo' },
  { id: 'PHP', name: 'Filipenses', chapters: 4, testament: 'Novo' },
  { id: 'COL', name: 'Colossenses', chapters: 4, testament: 'Novo' },
  { id: '1TH', name: '1 Tessalonicenses', chapters: 5, testament: 'Novo' },
  { id: '2TH', name: '2 Tessalonicenses', chapters: 3, testament: 'Novo' },
  { id: '1TI', name: '1 Timóteo', chapters: 6, testament: 'Novo' },
  { id: '2TI', name: '2 Timóteo', chapters: 4, testament: 'Novo' },
  { id: 'TIT', name: 'Tito', chapters: 3, testament: 'Novo' },
  { id: 'PHM', name: 'Filemom', chapters: 1, testament: 'Novo' },
  { id: 'HEB', name: 'Hebreus', chapters: 13, testament: 'Novo' },
  { id: 'JAS', name: 'Tiago', chapters: 5, testament: 'Novo' },
  { id: '1PE', name: '1 Pedro', chapters: 5, testament: 'Novo' },
  { id: '2PE', name: '2 Pedro', chapters: 3, testament: 'Novo' },
  { id: '1JN', name: '1 João', chapters: 5, testament: 'Novo' },
  { id: '2JN', name: '2 João', chapters: 1, testament: 'Novo' },
  { id: '3JN', name: '3 João', chapters: 1, testament: 'Novo' },
  { id: 'JUD', name: 'Judas', chapters: 1, testament: 'Novo' },
  { id: 'REV', name: 'Apocalipse', chapters: 22, testament: 'Novo' },
];
